

ID_CONDITIONS = {
                 "F180":"BootSoftwareIdentificationDataIdentifier",
                 "F181":"ApplicationSoftwareIdentificationDataIdentifier",
                 "F182":"ApplicationDataIdentification",
                 "F186":"ActiveDiagnosticSessionDataIdentifier",
                 "F18A":"SystemSupplierIdentifierDataIdentifier",
                 "F18B":"ECUManufacturingDateDataIdentifier",
                 "F18C":"ECUSerialNumberDataIdentifier",
                 "F190":"VINDataIdentifier",
                 "F191":"vehicleManufacturerECUHardwareNumberDataIdentifier",
                 "F192":"systemSupplierECUHardwareNumberDataIdentifier",
                 "F193":"systemSupplierECUHardwareVersionNumberDataIdentifier",
                 "F194":"systemSupplierECUSoftwareNumberDataIdentifier",
                 "F195":"systemSupplierECUSoftwareVersionNumberDataIdentifier",
                 "F197":"systemNameOrEngineTypeDataIdentifier",
                 "F198":"repairShopCodeOrTesterSerialNumberDataIdentifier",
                 "F199":"programmingDateDataIdentifier",
                 "F19B":"calibrationDateDataIdentifier",
                 "F19C":"calibrationEquipmentSoftwareNumberDataIdentifier",
                 "F19D":"ECUInstallationDateDataIdentifier",
                 "F19E":"ODXFileDataIdentifier",
                 "F101":"LMM specific",
                 "0200":"BOOT FLAG",
                 "0201":"HISTORY ZONE",
                 "B100":"Motor Temp - Max Start",
                 "B101":"Motor Temp - Max Cut",
                 "B102":"Bus Voltage - Max Start",
                 "B103":"Bus Voltage - Max Cut",
                 "B104":"Bus Voltage - Min Start",
                 "B105":"Bus Voltage - Min Cut",
                 "B106":"Hill Assisst Activation ",
                 "B107":"Assist Hill Hold timeout",
                 "B108":"Assist Rollback speed",
                 "B109":"Assist Brake Hold time",
                 "B10A":"Assist Minimum Torque",
                 "B10B":"Assist Brake Press Debounce time",
                 "B10C":"Assist Drive timeout time",
                 "B10D":"Angle Offset",
                 "B10E":"Forward Max Speed Limit Value",
                 "B10F":"Reverse Max Speed Limit Value",
                 "B110":"Actual Motor Speed ",
                 "B111":"Actual Torque",
                 "B112":"MCU_Counter1_20",
                 "B113":"Motor_Current_Measured",
                 "B114":"MCU_Board_temp",
                 "B116":"MCU_IP_DCBus_Voltage",
                 "B117":"MCU_Operating_Mode",
                 "B118":"Motor_Power_Measured",
                 "B119":"Motor_Winding-Temp",
                 "B11A":"MCU_IP_DC_Current",
                 "B11B":"Id_Act",
                 "B11C":"Iq_Act",
                 "B11D":"VLL_rms",
                 "B11E":"Motor Over Speed Threshold",
                 "B11F":"Motor Max Current Command",
                 "B120":"Controller Temp - Max Start ",
                 "B121":"Controller Temp - Max Cut",
                 "B122":"Controller Temp - Min Start ",
                 "B123":"Controller Temp - Min Cut ",
                 "B124":"Motor Temp - Min Start ",
                 "B125":"Motor Temp - Min Cut ",
                 "B126":"Max Bus Drive Current Limit Value",
                 "B127":"Max Bus Regen Current Limit Value",
                 "B128":"ADC Current Factor, Phase U ",
                 "B129":"ADC Current Factor, Phase V",
                 "B12A":"ADC Current Factor, Bus",
                 "B12B":"Ramp Up Drive",
                 "B12C":"Ramp Up regen",
                 "B12D":"Ramp Down",
                 "B12E":"Power Max",
                 "B12F":"Rotor Position",
                 "B130":"Frequency",
                 "0304":"Access Timing Parameters"

                 }

