#Application Software  Identification F181
send 22 F181

#Network Management Enable
#send 2E F1D4 01
#send 22 F1D4

#Network Management Disable
#send 2E F1D4 00
#send 22 F1D4

#CriticalCANSignalInvalidTime (Default 50, Scale 10)
send 2E F1D5 00 32 00 00 00 00
send 22 F1D5

#MainCANBusOffHealingTime (Default 1000, Scale 10)
send 2E F1D5 00 00 03 E8 00 00
send 22 F1D5

#CANTimeoutSincePowerup (Default 2000, Scale 20)
send 2E F1D5 00 00 00 00 07 D0
send 22 F1D5





