

ID_CONDITIONS = {"F18B":"ECU Manufacturing Date",
                 "F18C":"ECU Serial Number",
                 "F190":"VIN-Vehicle Identification Number",
                 "F197":"System Name/Engine Type",
                 "F198":"Repair Shop Code/Tester Serial Number",
                 "F180":"Boot Software Identification",
                 "F181":"Application Software Identification",
                 "F182":"Application Data Identification",
                 "F187":"Vehicle Manufacturer spare part number",
                 "F18A":"System Supplier Identifier",
                 "0100":"Model number",
                 "F199":"Programming Date",
                 "F19D":"ECU Installation Date",
                 "F193":"System Supplier ECU Hardware Version Number",
                 "F194":"System Supplier ECU Software Number",
                 "F195":"System Supplier ECU Software Version Number",
                 "F1F0":"System Supplier part number",
                 "0101":"Variant Code",
                 "0102":"Feature Code",
                 "F186":"Active Diagnostic Session",
                 "1500":"MCU EOL Calibration / Resolver Offset Calibration information",
                 "0304":"Access Timing Parameters",
                 "F1B0":"Odometer",
                 "F1B1":"Battery Voltage",
                 "F1B2":"Vehicle Speed",
                 "F1B3":"Motor speed",
                 "F1B4":"Reset Reason",
                 "F1B5":"Reset Counter",
                 "F1B6":"Ignition Counter",
                 "0303":"Security level",
                 "0201":"HISTORY ZONE",
                 "F1B9":"Snapshot Data",
                 "078E":"Freeze Frame Data",
                 "F1D4":"Network Management Enable",
                 "0200":"BOOT FLAG",
                 "23F9":"Wakeup Wait Timer",
                 "23FA":"Wakeup Sync Timer",
                 "23FC":"Normal Min Timeout Timer",
                 "23FB":"Sleep Wait Timer",
                 "249C":"DTC Enable/Disable",

                 }

